name: Bad Tango
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#53250b'
    - '#835639'
    - '#c9cbc4'
  brandStrength: 0.3125
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
