name: Bad Tango
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Bad Tango
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151c26'
    - '#3e505e'
    - '#9a814d'
    - '#dbc8cc'
    - '#e1f7fe'
  brandStrength: 1
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
