name: Bad Tango
favicon: null
layout_spectrum: 0.1390297447796911
typography_spectrum: 0.615907499101013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4847501548938453
  lightness: 0.8478772749658674
  saturation: 0.2613480044528842
  rhythmicContrast: 0.6525393633637577
purpose: []
